CREATE TABLE `user_session` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `session_token` VARCHAR(128) NOT NULL COMMENT '会话token或token指纹',
  `refresh_token` VARCHAR(128) DEFAULT NULL COMMENT '刷新token或token指纹',
  `session_status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1有效 2已退出 3已过期 4被踢下线',
  `login_type` VARCHAR(32) NOT NULL COMMENT '登录方式：mobile_sms/apple/email',
  `device_id` VARCHAR(128) DEFAULT NULL COMMENT '设备ID',
  `device_name` VARCHAR(128) DEFAULT NULL COMMENT '设备名称',
  `device_os` VARCHAR(32) DEFAULT NULL COMMENT '系统类型：ios/android/web',
  `app_version` VARCHAR(32) DEFAULT NULL COMMENT 'App版本',
  `login_ip` VARCHAR(64) DEFAULT NULL COMMENT '登录IP',
  `login_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '登录时间',
  `last_active_at` DATETIME DEFAULT NULL COMMENT '最后活跃时间',
  `expire_at` DATETIME NOT NULL COMMENT '会话过期时间',
  `logout_at` DATETIME DEFAULT NULL COMMENT '退出时间',
  `ext_json` JSON DEFAULT NULL COMMENT '扩展信息',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_session_token` (`session_token`),
  UNIQUE KEY `uk_refresh_token` (`refresh_token`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_user_status` (`user_id`, `session_status`),
  KEY `idx_expire_at` (`expire_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户登录会话表';