CREATE TABLE `sms_code_log` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `biz_type` VARCHAR(32) NOT NULL COMMENT '业务类型：login/bind_mobile/reset_mobile',
  `phone` VARCHAR(32) NOT NULL COMMENT '手机号',
  `country_code` VARCHAR(8) NOT NULL DEFAULT '+86' COMMENT '国家区号',
  `code_hash` VARCHAR(128) NOT NULL COMMENT '验证码哈希，不存明文',
  `code_last4` VARCHAR(8) DEFAULT NULL COMMENT '验证码后4位，便于排查',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1待验证 2已验证 3已失效 4验证失败次数过多',
  `send_channel` VARCHAR(32) DEFAULT 'sms' COMMENT '发送渠道',
  `send_status` TINYINT NOT NULL DEFAULT 1 COMMENT '发送状态：1成功 2失败',
  `send_message` VARCHAR(255) DEFAULT NULL COMMENT '发送结果描述',
  `request_ip` VARCHAR(64) DEFAULT NULL COMMENT '请求IP',
  `device_id` VARCHAR(128) DEFAULT NULL COMMENT '设备ID',
  `scene_key` VARCHAR(64) DEFAULT NULL COMMENT '场景幂等key/链路key',
  `expire_at` DATETIME NOT NULL COMMENT '过期时间',
  `verified_at` DATETIME DEFAULT NULL COMMENT '验证通过时间',
  `error_count` INT NOT NULL DEFAULT 0 COMMENT '验证码错误次数',
  `max_error_count` INT NOT NULL DEFAULT 5 COMMENT '最大允许错误次数',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '发送时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_phone_biz_created` (`phone`, `biz_type`, `created_at`),
  KEY `idx_phone_status` (`phone`, `status`),
  KEY `idx_expire_at` (`expire_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='短信验证码记录表';